import type { RecommendationCandidate } from "@/lib/film-recommendations";

export const FILM_CATALOG_UPDATED_AT = "2026-08-15";

export const FILM_CATALOG: RecommendationCandidate[] = [
  { id: "obsession-2026", title: "Obsession", year: 2026, mediaType: "movie", genreIds: [27, 53, 9648], keywords: ["obsession", "supernatural", "curse", "suspense", "psychological_horror"], people: ["Michael Johnston", "Inde Navarrette", "Cooper Tomlinson"], director: "Curry Barker", popularity: 98, genreLabel: "Horreur · Thriller psychologique", pitch: "Un jeune homme utilise un objet capable d’exaucer un souhait pour être aimé par son amie d’enfance. Le vœu fonctionne beaucoup trop bien et transforme cette relation en menace incontrôlable.", runtime: "1 h 49", rating: 7.9, certification: "16", originalTitle: "Obsession" },
  { id: "backrooms-2026", title: "Backrooms", year: 2026, mediaType: "movie", genreIds: [27, 53, 9648], keywords: ["liminal_spaces", "mystery", "survival", "suspense", "creature"], people: ["Chiwetel Ejiofor", "Renate Reinsve", "Mark Duplass"], director: "Kane Parsons", popularity: 95, genreLabel: "Horreur · Mystère", pitch: "Une porte apparue dans le sous-sol d’un magasin ouvre sur un labyrinthe de pièces impossibles et d’espaces liminaux où la frontière entre réalité et piège mental se dérègle.", runtime: "1 h 51", rating: 6.9, certification: "12", originalTitle: "Backrooms" },
  { id: "prisoners-2013", title: "Prisoners", year: 2013, mediaType: "movie", genreIds: [53, 80, 18], keywords: ["investigation", "mystery", "crime", "suspense"], people: ["Hugh Jackman", "Jake Gyllenhaal", "Viola Davis"], director: "Denis Villeneuve", popularity: 82, genreLabel: "Thriller · Crime", pitch: "Après la disparition de deux fillettes, un père refuse d’attendre que l’enquête avance et franchit progressivement ses propres limites.", runtime: "2 h 33", rating: 8.1, certification: "Thriller intense", originalTitle: "Prisoners" },
  { id: "talk-to-me-2022", title: "Talk to Me", year: 2022, mediaType: "movie", genreIds: [27, 53], keywords: ["supernatural", "possession", "suspense", "survival"], people: ["Sophie Wilde", "Alexandra Jensen", "Joe Bird"], director: "Danny Philippou", popularity: 76, genreLabel: "Horreur · Surnaturel", pitch: "Un groupe d’amis découvre comment invoquer des esprits avec une main embaumée. Le jeu devient rapidement incontrôlable.", runtime: "1 h 35", rating: 7.1, certification: "Horreur", originalTitle: "Talk to Me" },
  { id: "invisible-man-2020", title: "The Invisible Man", year: 2020, mediaType: "movie", genreIds: [27, 53, 878], keywords: ["suspense", "survival", "mystery", "stalking"], people: ["Elisabeth Moss", "Aldis Hodge", "Storm Reid"], director: "Leigh Whannell", popularity: 72, genreLabel: "Thriller · Horreur", pitch: "Après avoir fui une relation violente, Cecilia pense être traquée par une présence que personne d’autre ne peut voir.", runtime: "2 h 04", rating: 7.1, certification: "Thriller horrifique", originalTitle: "The Invisible Man" },
  { id: "evil-dead-rise-2023", title: "Evil Dead Rise", year: 2023, mediaType: "movie", genreIds: [27, 53], keywords: ["possession", "supernatural", "survival", "gore"], people: ["Lily Sullivan", "Alyssa Sutherland", "Morgan Davies"], director: "Lee Cronin", popularity: 79, genreLabel: "Horreur · Gore", pitch: "Les retrouvailles de deux sœurs sont interrompues par l’apparition de démons capables de prendre possession des corps.", runtime: "1 h 36", rating: 7.0, certification: "Horreur gore", originalTitle: "Evil Dead Rise", posterUrl: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg" },
  { id: "missing-2023", title: "Missing", year: 2023, mediaType: "movie", genreIds: [53, 9648, 18], keywords: ["investigation", "mystery", "twist", "suspense"], people: ["Storm Reid", "Joaquim de Almeida", "Nia Long"], director: "Will Merrick", popularity: 64, genreLabel: "Thriller · Mystère", pitch: "Quand sa mère disparaît à l’étranger, June utilise les outils numériques à sa disposition pour tenter de comprendre ce qui s’est passé.", runtime: "1 h 51", rating: 7.4, certification: "Thriller", originalTitle: "Missing" },
  { id: "watcher-2022", title: "Watcher", year: 2022, mediaType: "movie", genreIds: [53, 27], keywords: ["stalking", "suspense", "murder", "mystery"], people: ["Maika Monroe", "Karl Glusman", "Burn Gorman"], director: "Chloe Okuno", popularity: 49, genreLabel: "Thriller", pitch: "Nouvellement installée à Bucarest, Julia remarque un homme qui semble l’observer depuis l’immeuble d’en face.", runtime: "1 h 36", rating: 6.5, certification: "Thriller", originalTitle: "Watcher" },
  { id: "dexter-2006", title: "Dexter", year: 2006, mediaType: "tv", genreIds: [80, 18, 9648], keywords: ["serial_killer", "crime", "investigation", "murder"], people: ["Michael C. Hall", "Jennifer Carpenter", "David Zayas"], popularity: 88, genreLabel: "Crime · Thriller", pitch: "Expert médico-légal le jour, Dexter Morgan mène la nuit une seconde vie où il traque des criminels ayant échappé à la justice.", runtime: "8 saisons", rating: 8.2, certification: "Série crime", originalTitle: "Dexter" },
  { id: "bri-2023", title: "B.R.I.", year: 2023, mediaType: "tv", genreIds: [80, 18, 28], keywords: ["crime", "investigation", "police", "suspense"], people: ["Sofian Khammes", "Ophélie Bau", "Théo Christine"], popularity: 40, genreLabel: "Policier · Action", pitch: "Une unité de la BRI de Versailles navigue entre interventions, affaires criminelles et rivalités internes.", runtime: "Série", rating: 7.2, certification: "Policier", originalTitle: "B.R.I." },
];

export function getFilmById(id: string) {
  return FILM_CATALOG.find((item) => item.id === id);
}

export function coverFor(candidate: RecommendationCandidate) {
  return candidate.posterUrl || `https://placehold.co/600x900/090a0c/ffffff?text=${encodeURIComponent(candidate.title)}`;
}
