import type { RecommendationCandidate } from "@/lib/film-recommendations";

export const FILM_CATALOG_UPDATED_AT = "2026-08-17";

export const FILM_CATALOG: RecommendationCandidate[] = [
  { id: "obsession-2026", title: "Obsession", year: 2026, mediaType: "movie", genreIds: [27, 53, 9648], keywords: ["obsession", "supernatural", "curse", "suspense", "psychological_horror"], people: ["Michael Johnston", "Inde Navarrette", "Cooper Tomlinson"], director: "Curry Barker", popularity: 98, genreLabel: "Horreur · Thriller psychologique", pitch: "Un jeune homme utilise un objet capable d’exaucer un souhait pour être aimé par son amie d’enfance. Le vœu fonctionne beaucoup trop bien et transforme cette relation en menace incontrôlable.", runtime: "1 h 49", rating: 7.9, certification: "16", originalTitle: "Obsession" },
  { id: "backrooms-2026", title: "Backrooms", year: 2026, mediaType: "movie", genreIds: [27, 53, 9648], keywords: ["liminal_spaces", "mystery", "survival", "suspense", "creature"], people: ["Chiwetel Ejiofor", "Renate Reinsve", "Mark Duplass"], director: "Kane Parsons", popularity: 95, genreLabel: "Horreur · Mystère", pitch: "Une porte apparue dans le sous-sol d’un magasin ouvre sur un labyrinthe de pièces impossibles et d’espaces liminaux où la frontière entre réalité et piège mental se dérègle.", runtime: "1 h 51", rating: 6.9, certification: "12", originalTitle: "Backrooms" },
  { id: "prisoners-2013", title: "Prisoners", year: 2013, mediaType: "movie", genreIds: [53, 80, 18], keywords: ["investigation", "mystery", "crime", "suspense"], people: ["Hugh Jackman", "Jake Gyllenhaal", "Viola Davis"], director: "Denis Villeneuve", popularity: 82, genreLabel: "Thriller · Crime", pitch: "Après la disparition de deux fillettes, un père refuse d’attendre que l’enquête avance et franchit progressivement ses propres limites.", runtime: "2 h 33", rating: 8.1, certification: "Thriller intense", originalTitle: "Prisoners" },
  { id: "talk-to-me-2022", title: "Talk to Me", year: 2022, mediaType: "movie", genreIds: [27, 53], keywords: ["supernatural", "possession", "suspense", "survival"], people: ["Sophie Wilde", "Alexandra Jensen", "Joe Bird"], director: "Danny Philippou", popularity: 76, genreLabel: "Horreur · Surnaturel", pitch: "Un groupe d’amis découvre comment invoquer des esprits grâce à une mystérieuse main embaumée. Ce qui commence comme un jeu viral bascule lorsqu’ils vont trop loin et ouvrent une porte qu’ils ne savent plus refermer.", runtime: "1 h 35", rating: 7.1, certification: "Horreur", originalTitle: "Talk to Me", posterUrl: "https://www.dvd-trailers.gr/posters/mila_mou_2022.jpg" },
  { id: "invisible-man-2020", title: "The Invisible Man", year: 2020, mediaType: "movie", genreIds: [27, 53, 878], keywords: ["suspense", "survival", "mystery", "stalking"], people: ["Elisabeth Moss", "Aldis Hodge", "Storm Reid"], director: "Leigh Whannell", popularity: 72, genreLabel: "Thriller · Horreur", pitch: "Après avoir fui une relation violente, Cecilia pense être traquée par une présence que personne d’autre ne peut voir.", runtime: "2 h 04", rating: 7.1, certification: "Thriller horrifique", originalTitle: "The Invisible Man" },
  { id: "evil-dead-rise-2023", title: "Evil Dead Rise", year: 2023, mediaType: "movie", genreIds: [27, 53], keywords: ["possession", "supernatural", "survival", "gore"], people: ["Lily Sullivan", "Alyssa Sutherland", "Morgan Davies"], director: "Lee Cronin", popularity: 79, genreLabel: "Horreur · Gore", pitch: "Les retrouvailles de deux sœurs sont interrompues par l’apparition de démons capables de prendre possession des corps.", runtime: "1 h 36", rating: 7.0, certification: "Horreur gore", originalTitle: "Evil Dead Rise", posterUrl: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg" },
  { id: "missing-2023", title: "Missing", year: 2023, mediaType: "movie", genreIds: [53, 9648, 18], keywords: ["investigation", "mystery", "twist", "suspense"], people: ["Storm Reid", "Joaquim de Almeida", "Nia Long"], director: "Will Merrick", popularity: 64, genreLabel: "Thriller · Mystère", pitch: "Quand sa mère disparaît à l’étranger, June utilise les outils numériques à sa disposition pour tenter de comprendre ce qui s’est passé.", runtime: "1 h 51", rating: 7.4, certification: "Thriller", originalTitle: "Missing" },
  { id: "watcher-2022", title: "Watcher", year: 2022, mediaType: "movie", genreIds: [53, 27], keywords: ["stalking", "suspense", "murder", "mystery"], people: ["Maika Monroe", "Karl Glusman", "Burn Gorman"], director: "Chloe Okuno", popularity: 49, genreLabel: "Thriller · Horreur", pitch: "Julia s’installe à Bucarest avec son mari et se retrouve souvent seule dans leur appartement. Depuis sa fenêtre, elle remarque un homme dans l’immeuble d’en face qui semble l’observer, tandis qu’un tueur en série rôde dans la ville.", runtime: "1 h 36", rating: 6.5, certification: "Thriller", originalTitle: "Watcher", posterUrl: "https://open-images.acast.com/shows/664259a87c2bf1001333ae3b/1726061571464-d77caddc-82a5-4a4a-a0d1-209fce2acb6c.jpeg?height=750" },
  { id: "dexter-2006", title: "Dexter", year: 2006, mediaType: "tv", genreIds: [80, 18, 9648], keywords: ["serial_killer", "crime", "investigation", "murder"], people: ["Michael C. Hall", "Jennifer Carpenter", "David Zayas"], popularity: 88, genreLabel: "Crime · Thriller", pitch: "Expert médico-légal spécialisé dans les traces de sang à Miami, Dexter Morgan mène en secret une seconde vie de justicier meurtrier et cible des criminels ayant échappé à la justice.", runtime: "8 saisons", rating: 8.2, certification: "Série crime", originalTitle: "Dexter", posterUrl: "https://www.ecartelera.com/carteles-series/100/116/001.jpg" },
  { id: "bri-2023", title: "B.R.I.", year: 2023, mediaType: "tv", genreIds: [80, 18, 28], keywords: ["crime", "investigation", "police", "suspense"], people: ["Sofian Khammes", "Ophélie Bau", "Théo Christine"], popularity: 40, genreLabel: "Policier · Action", pitch: "À la BRI de Versailles, Saïd prend la tête d’une équipe de jeunes policiers d’élite. Il doit imposer ses méthodes alors qu’une guerre des gangs menace d’embraser Paris et que les frontières entre loyauté, terrain et grand banditisme se brouillent.", runtime: "Série", rating: 7.2, certification: "Policier", originalTitle: "B.R.I.", posterUrl: "https://medias.unifrance.org/medias/223/187/310239/format_page/b-r-i.jpg" },
];

export function getFilmById(id: string) {
  return FILM_CATALOG.find((item) => item.id === id);
}

export function coverFor(candidate: RecommendationCandidate) {
  return candidate.posterUrl || `data:image/svg+xml,${encodeURIComponent(`<svg width="600" height="900" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" fill="#111318"/><text x="50%" y="48%" fill="#f4f4f5" font-size="34" font-family="sans-serif" text-anchor="middle">${candidate.title.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;")}</text><text x="50%" y="54%" fill="#71717a" font-size="18" font-family="sans-serif" text-anchor="middle">ANGEL OS · SECOURS LOCAL</text></svg>`)}`;
}
