import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { LockKeyhole, Search, ShieldCheck, Sparkles, Video, X } from "lucide-react";
import { FlameMark } from "./social-v2-shared";

const STEPS=[
  {icon:Sparkles,title:"Bienvenue sur Flamme",text:"Recherche, réseau social, vidéos, forum et messagerie réunis dans une interface simple.",accent:"from-[#CE654B] to-[#A84D38]"},
  {icon:LockKeyhole,title:"Pensé pour la confidentialité",text:"Messages chiffrés de bout en bout, profils sous pseudonyme et mode anonyme pour publier dans le forum.",accent:"from-[#172638] to-[#334A62]"},
  {icon:Video,title:"Un fil visuel et rapide",text:"Publications façon Instagram, réactions multiples et vidéos verticales immersives avec défilement plein écran.",accent:"from-[#6554C0] to-[#CE654B]"},
  {icon:Search,title:"Le Web dans Flamme",text:"Qwant ou Lilo, services français et Mistral sans quitter l’interface sociale.",accent:"from-[#168A72] to-[#172638]"},
];

export function FlammeOnboardingV4({onDone}:{onDone:()=>void}){const [index,setIndex]=useState(0);const step=STEPS[index];const Icon=step.icon;const done=()=>{try{localStorage.setItem("flamme-onboarding-v4","done")}catch{}onDone()};return <div className="fixed inset-0 z-[500] flex items-center justify-center overflow-hidden bg-[#101216] p-4 text-white"><div className="absolute inset-0 opacity-40"><div className="absolute -left-24 top-[-8%] h-80 w-80 rounded-full bg-[#CE654B] blur-[120px]"/><div className="absolute -right-20 bottom-[-10%] h-80 w-80 rounded-full bg-[#6554C0] blur-[130px]"/></div><button onClick={done} className="absolute right-4 top-4 z-20 flex h-10 w-10 items-center justify-center rounded-full bg-white/10 backdrop-blur" aria-label="Fermer"><X className="h-5 w-5"/></button><div className="relative z-10 w-full max-w-md"><div className="mb-8 flex items-center justify-center gap-2"><FlameMark className="h-11 w-11"/><strong className="text-xl tracking-tight">Flamme</strong></div><AnimatePresence mode="wait"><motion.div key={index} initial={{opacity:0,y:24,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-18,scale:.98}} transition={{duration:.32,ease:[.2,.8,.2,1]}} className="rounded-[28px] border border-white/10 bg-white/[.07] p-6 text-center shadow-2xl backdrop-blur-xl"><motion.div initial={{scale:.65,rotate:-12}} animate={{scale:1,rotate:0}} transition={{type:"spring",stiffness:220,damping:16}} className={`mx-auto flex h-24 w-24 items-center justify-center rounded-[28px] bg-gradient-to-br ${step.accent} shadow-xl`}><Icon className="h-11 w-11"/></motion.div><h1 className="mt-6 text-2xl font-extrabold tracking-tight">{step.title}</h1><p className="mx-auto mt-3 max-w-sm text-sm leading-relaxed text-white/70">{step.text}</p>{index===1&&<div className="mt-5 grid grid-cols-2 gap-2 text-left text-[11px]"><span className="rounded-xl bg-white/8 p-3"><ShieldCheck className="mb-2 h-4 w-4 text-emerald-300"/>Signalements assistés par IA</span><span className="rounded-xl bg-white/8 p-3"><LockKeyhole className="mb-2 h-4 w-4 text-sky-300"/>Clés privées conservées sur l’appareil</span></div>}</motion.div></AnimatePresence><div className="mt-5 flex items-center justify-center gap-1.5">{STEPS.map((_,i)=><span key={i} className={`h-1.5 rounded-full transition-all ${i===index?"w-7 bg-white":"w-1.5 bg-white/30"}`}/>)}</div><div className="mt-6 flex gap-2">{index>0&&<button onClick={()=>setIndex(value=>value-1)} className="flex-1 rounded-full bg-white/10 py-3 text-sm font-bold">Retour</button>}<button onClick={()=>index<STEPS.length-1?setIndex(value=>value+1):done()} className="flex-[1.7] rounded-full bg-[#CE654B] py-3 text-sm font-extrabold shadow-lg">{index<STEPS.length-1?"Continuer":"Entrer dans Flamme"}</button></div><p className="mt-4 text-center text-[10px] leading-relaxed text-white/40">Flamme est en bêta. Le mode anonyme masque votre identité publique mais ne supprime pas les protections anti-abus côté serveur.</p></div></div>}
