import { useCallback, useEffect, useState, type FormEvent } from "react";
import { BadgeCheck, Camera, ExternalLink, Image as ImageIcon, MapPin, MoreHorizontal, ShieldCheck, UserPlus, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Avatar, Card, Empty, Modal, SecureMedia, VerifiedName, cx, publicAvatarUrl, reportContent, safeExt, socialDb, socialErrorMessage, type Media, type Post, type Profile } from "./social-v2-shared";

type Tab="posts"|"about"|"photos";

function validate(file:File){if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw new Error("JPG, PNG ou WebP uniquement.");if(file.size>5*1024*1024)throw new Error("5 Mo maximum.")}

function ProfilePosts({profile}:{profile:Profile}){
  const [posts,setPosts]=useState<Post[]>([]);const [media,setMedia]=useState<Media[]>([]);const [loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;void(async()=>{const {data}=await socialDb.from("flamme_posts").select("*").eq("author_id",profile.id).is("group_id",null).order("created_at",{ascending:false}).limit(40);const rows=(data??[]) as Post[];const ids=rows.map(row=>row.id);const {data:mediaRows}=ids.length?await socialDb.from("flamme_post_media").select("*").in("post_id",ids).order("position"):{data:[]};if(active){setPosts(rows);setMedia((mediaRows??[]) as Media[]);setLoading(false)}})();return()=>{active=false}},[profile.id]);
  if(loading)return <Card className="p-8 text-center text-sm text-slate-500">Chargement…</Card>;
  if(!posts.length)return <Empty title="Aucune publication" text="Les publications de ce profil apparaîtront ici."/>;
  return <div className="space-y-2">{posts.map(post=>{const items=media.filter(item=>item.post_id===post.id);return <Card key={post.id} className="overflow-hidden"><div className="flex items-center gap-2.5 p-3"><Avatar profile={profile} size="sm"/><div className="min-w-0"><VerifiedName profile={profile} className="max-w-full text-sm font-extrabold dark:text-white"/><span className="block text-[10px] text-slate-500">{new Date(post.created_at).toLocaleDateString("fr-FR",{day:"numeric",month:"short"})}</span></div></div>{post.content&&<p className="whitespace-pre-wrap break-words px-3 pb-3 text-sm leading-relaxed dark:text-slate-100">{post.content}</p>}{items.length>0&&<div className={cx("grid gap-px bg-black/5",items.length>1&&"grid-cols-2")}>{items.slice(0,4).map(item=><div key={item.id} className={items.length===1?"max-h-[65dvh]":"aspect-square"}><SecureMedia bucket={item.bucket??"flamme-media"} path={item.path} type={item.media_type} className="h-full w-full object-cover"/></div>)}</div>}</Card>})}</div>;
}

function ProfilePhotos({profile}:{profile:Profile}){
  const [items,setItems]=useState<Media[]>([]);
  useEffect(()=>{void(async()=>{const {data:posts}=await socialDb.from("flamme_posts").select("id").eq("author_id",profile.id).limit(100);const ids=(posts??[]).map((row:{id:string})=>row.id);const {data}=ids.length?await socialDb.from("flamme_post_media").select("*").in("post_id",ids).eq("media_type","image").limit(100):{data:[]};setItems((data??[]) as Media[])})()},[profile.id]);
  if(!items.length)return <Empty icon={ImageIcon} title="Aucune photo" text="Les photos publiques apparaîtront ici."/>;
  return <div className="grid grid-cols-3 gap-0.5 overflow-hidden rounded-xl">{items.map(item=><div key={item.id} className="aspect-square bg-slate-100"><SecureMedia bucket={item.bucket??"flamme-media"} path={item.path} type="image" className="h-full w-full object-cover"/></div>)}</div>;
}

export function ProfileViewV4({me,profile,onBack,onMeChanged}:{me:Profile;profile:Profile;onBack?:()=>void;onMeChanged?:(profile:Profile)=>void}){
  const own=me.id===profile.id;const [tab,setTab]=useState<Tab>("posts");const [stats,setStats]=useState({followers:0,following:0,posts:0});const [following,setFollowing]=useState<"none"|"pending"|"accepted">("none");const [edit,setEdit]=useState(false);const [menu,setMenu]=useState(false);const [display,setDisplay]=useState(profile.display_name);const [bio,setBio]=useState(profile.bio||"");const [city,setCity]=useState(profile.city||"");const [website,setWebsite]=useState(profile.website||"");const [avatar,setAvatar]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [admin,setAdmin]=useState(false);const [verified,setVerified]=useState(Boolean(profile.is_verified));const [preview,setPreview]=useState<string|null>(null);

  const load=useCallback(async()=>{const [{count:followers},{count:followingCount},{count:posts},{data:relation},{data:isAdmin}]=await Promise.all([socialDb.from("flamme_follows").select("id",{count:"exact",head:true}).eq("following_id",profile.id).eq("status","accepted"),socialDb.from("flamme_follows").select("id",{count:"exact",head:true}).eq("follower_id",profile.id).eq("status","accepted"),socialDb.from("flamme_posts").select("id",{count:"exact",head:true}).eq("author_id",profile.id),own?Promise.resolve({data:null}):socialDb.from("flamme_follows").select("status").eq("follower_id",me.id).eq("following_id",profile.id).maybeSingle(),socialDb.rpc("flamme_is_admin",{u:me.id})]);setStats({followers:followers??0,following:followingCount??0,posts:posts??0});if(relation?.status)setFollowing(relation.status);setAdmin(Boolean(isAdmin));},[me.id,own,profile.id]);
  useEffect(()=>{void load()},[load]);useEffect(()=>{setDisplay(profile.display_name);setBio(profile.bio||"");setCity(profile.city||"");setWebsite(profile.website||"");setVerified(Boolean(profile.is_verified))},[profile]);
  useEffect(()=>{if(!avatar){setPreview(null);return}const url=URL.createObjectURL(avatar);setPreview(url);return()=>URL.revokeObjectURL(url)},[avatar]);

  const toggleFollow=async()=>{if(own)return;if(following!=="none"){await socialDb.from("flamme_follows").delete().eq("follower_id",me.id).eq("following_id",profile.id);setFollowing("none")}else{const status=profile.is_private?"pending":"accepted";await socialDb.from("flamme_follows").insert({follower_id:me.id,following_id:profile.id,status});setFollowing(status)}void load()};
  const save=async(event:FormEvent)=>{event.preventDefault();if(!own||busy)return;setBusy(true);setError(null);let avatarPath=profile.avatar_path??null;let uploaded:string|null=null;try{if(avatar){validate(avatar);uploaded=`${me.id}/avatars/${crypto.randomUUID()}.${safeExt(avatar)}`;const {error:uploadError}=await supabase.storage.from("flamme-avatars").upload(uploaded,avatar,{upsert:false,cacheControl:"3600"});if(uploadError)throw uploadError;avatarPath=uploaded}const {data,error:updateError}=await socialDb.from("flamme_profiles").update({display_name:display.trim(),bio:bio.trim(),city:city.trim()||null,website:website.trim()||null,avatar_path:avatarPath}).eq("id",me.id).select("*").single();if(updateError||!data)throw updateError??new Error("Profil impossible à enregistrer.");if(uploaded&&profile.avatar_path&&profile.avatar_path!==uploaded)await supabase.storage.from("flamme-avatars").remove([profile.avatar_path]).then(()=>undefined,()=>undefined);setAvatar(null);setEdit(false);onMeChanged?.(data as Profile)}catch(cause){if(uploaded)await supabase.storage.from("flamme-avatars").remove([uploaded]).then(()=>undefined,()=>undefined);setError(socialErrorMessage(cause,"Profil impossible à enregistrer."))}finally{setBusy(false)}};
  const certify=async()=>{const next=!verified;const {error:rpcError}=await socialDb.rpc("flamme_set_verified",{target_user:profile.id,verified:next});if(rpcError)return setError(socialErrorMessage(rpcError,"Action administrateur impossible."));setVerified(next);if(own)onMeChanged?.({...profile,is_verified:next})};
  const report=async()=>{const details=prompt("Pourquoi signalez-vous ce profil ?","");if(details===null)return;try{await reportContent("profile",profile.id,details,"impersonation");alert("Signalement envoyé.")}catch(cause){alert(socialErrorMessage(cause,"Signalement impossible."))}};
  const block=async()=>{if(own)return;if(!confirm("Bloquer ce compte ?"))return;await socialDb.from("flamme_blocks").insert({blocker_id:me.id,blocked_id:profile.id}).then(()=>undefined,()=>undefined);onBack?.()};

  const shown={...profile,is_verified:verified} as Profile;const avatarUrl=preview||publicAvatarUrl(profile.avatar_path);
  return <div className="mx-auto w-full max-w-[680px] space-y-2 px-0 sm:px-1">
    <Card className="overflow-visible p-4 sm:p-5">
      <div className="flex min-w-0 items-start gap-3 sm:gap-4">
        <div className="relative shrink-0">{avatarUrl?<img src={avatarUrl} alt="" className="h-20 w-20 rounded-full object-cover ring-1 ring-black/5 sm:h-24 sm:w-24"/>:<Avatar profile={shown} size="xl"/>}{own&&<button onClick={()=>setEdit(true)} className="absolute -bottom-1 -right-1 flex h-8 w-8 items-center justify-center rounded-full bg-[#E4E6EB] shadow dark:bg-[#2a2e35]" aria-label="Modifier la photo"><Camera className="h-4 w-4"/></button>}</div>
        <div className="min-w-0 flex-1"><div className="flex min-w-0 items-center gap-2"><h1 className="min-w-0 truncate text-xl font-extrabold tracking-tight dark:text-white sm:text-2xl">{profile.display_name}</h1>{verified&&<BadgeCheck className="h-5 w-5 shrink-0 fill-[#1877F2] text-white"/>}</div><p className="truncate text-xs text-slate-500">@{profile.handle}</p>{profile.bio&&<p className="mt-2 line-clamp-3 break-words text-sm leading-relaxed text-slate-700 dark:text-slate-200">{profile.bio}</p>}
          <div className="mt-3 flex items-center gap-4 text-xs"><span><strong className="text-slate-900 dark:text-white">{stats.posts}</strong> <span className="text-slate-500">posts</span></span><span><strong className="text-slate-900 dark:text-white">{stats.followers}</strong> <span className="text-slate-500">abonnés</span></span><span><strong className="text-slate-900 dark:text-white">{stats.following}</strong> <span className="text-slate-500">suivis</span></span></div>
        </div>
        <div className="flex shrink-0 gap-1">{own?<button onClick={()=>setEdit(true)} className="rounded-lg bg-[#E4E6EB] px-3 py-2 text-xs font-extrabold dark:bg-white/10 dark:text-white">Modifier</button>:<button onClick={()=>void toggleFollow()} className={cx("rounded-lg px-3 py-2 text-xs font-extrabold",following==="accepted"?"bg-[#E4E6EB] dark:bg-white/10 dark:text-white":"bg-[#CE654B] text-white")}>{following==="accepted"?"Abonné":following==="pending"?"En attente":"Suivre"}</button>}<button onClick={()=>setMenu(value=>!value)} className="flex h-9 w-9 items-center justify-center rounded-lg text-slate-500 hover:bg-black/5 dark:hover:bg-white/5"><MoreHorizontal className="h-5 w-5"/></button></div>
      </div>
      {menu&&<div className="mt-3 grid gap-1 rounded-xl border bg-white p-1.5 text-xs shadow-lg dark:border-white/10 dark:bg-[#242830]">{admin&&<button onClick={()=>void certify()} className="flex items-center gap-2 rounded-lg px-3 py-2 text-left font-bold hover:bg-black/5 dark:hover:bg-white/5"><ShieldCheck className="h-4 w-4 text-[#1877F2]"/>{verified?"Retirer le badge officiel":"Certifier ce compte"}</button>}{!own&&<><button onClick={()=>void report()} className="rounded-lg px-3 py-2 text-left font-bold hover:bg-black/5 dark:hover:bg-white/5">Signaler le profil</button><button onClick={()=>void block()} className="rounded-lg px-3 py-2 text-left font-bold text-red-600 hover:bg-red-50">Bloquer</button></>}{onBack&&<button onClick={onBack} className="rounded-lg px-3 py-2 text-left font-bold hover:bg-black/5 dark:hover:bg-white/5">Retour</button>}</div>}
      <nav className="mt-4 flex border-t border-black/[.06] pt-2 dark:border-white/10">{([['posts','Publications'],['about','Infos'],['photos','Photos']] as Array<[Tab,string]>).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={cx("relative flex-1 py-2.5 text-xs font-bold text-slate-500",tab===id&&"text-[#CE654B]")}>{label}{tab===id&&<span className="absolute inset-x-3 bottom-0 h-0.5 rounded-full bg-[#CE654B]"/>}</button>)}</nav>
    </Card>
    {tab==="posts"&&<ProfilePosts profile={shown}/>} {tab==="photos"&&<ProfilePhotos profile={shown}/>} {tab==="about"&&<Card className="p-4"><div className="space-y-3 text-sm text-slate-600 dark:text-slate-300">{profile.bio&&<p className="whitespace-pre-wrap break-words leading-relaxed">{profile.bio}</p>}{profile.city&&<p className="flex items-center gap-2"><MapPin className="h-4 w-4 text-slate-400"/>{profile.city}</p>}{profile.website&&<a href={profile.website.startsWith("http")?profile.website:`https://${profile.website}`} target="_blank" rel="noreferrer" className="flex min-w-0 items-center gap-2 font-bold text-[#CE654B]"><ExternalLink className="h-4 w-4 shrink-0"/><span className="truncate">{profile.website}</span></a>}<p className="text-xs text-slate-400">Membre depuis {new Date(profile.created_at).toLocaleDateString("fr-FR",{month:"long",year:"numeric"})}</p></div></Card>}

    <Modal open={edit} onClose={()=>!busy&&setEdit(false)}><form onSubmit={save} className="p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-extrabold dark:text-white">Modifier le profil</h2><button type="button" onClick={()=>setEdit(false)} className="rounded-full bg-[#E4E6EB] p-2 dark:bg-white/10"><X className="h-4 w-4"/></button></div><div className="mt-5 flex items-center gap-3"><Avatar profile={shown} size="lg"/><label className="cursor-pointer rounded-lg bg-[#E4E6EB] px-3 py-2 text-xs font-bold dark:bg-white/10 dark:text-white"><Camera className="mr-1 inline h-4 w-4"/>Photo<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={event=>{const file=event.target.files?.[0]??null;if(file)try{validate(file);setAvatar(file);setError(null)}catch(cause){setError(socialErrorMessage(cause,"Image invalide."))}}}/></label></div><div className="mt-5 space-y-3"><label className="block text-xs font-bold text-slate-500">Nom<input required maxLength={80} value={display} onChange={event=>setDisplay(event.target.value)} className="mt-1 w-full rounded-lg border p-3 text-base font-normal dark:border-white/10 dark:bg-white/5 dark:text-white"/></label><label className="block text-xs font-bold text-slate-500">Bio<textarea maxLength={500} value={bio} onChange={event=>setBio(event.target.value)} className="mt-1 min-h-24 w-full rounded-lg border p-3 text-base font-normal dark:border-white/10 dark:bg-white/5 dark:text-white"/></label><label className="block text-xs font-bold text-slate-500">Ville<input maxLength={100} value={city} onChange={event=>setCity(event.target.value)} className="mt-1 w-full rounded-lg border p-3 text-base font-normal dark:border-white/10 dark:bg-white/5 dark:text-white"/></label><label className="block text-xs font-bold text-slate-500">Site web<input maxLength={300} value={website} onChange={event=>setWebsite(event.target.value)} className="mt-1 w-full rounded-lg border p-3 text-base font-normal dark:border-white/10 dark:bg-white/5 dark:text-white"/></label></div>{error&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>}<button disabled={busy||!display.trim()} className="mt-4 w-full rounded-lg bg-[#CE654B] py-3 text-sm font-extrabold text-white disabled:opacity-40">{busy?"Enregistrement…":"Enregistrer"}</button></form></Modal>
  </div>;
}
