export const siteFlow = [
  {
    step: "01",
    title: "Linux reste la cible du noyau",
    text: "Angel OS est conçu comme un noyau d'orchestration portable, avec Linux comme environnement serveur de référence. Le site web et Angel OS IA sont des couches au-dessus du noyau, pas le noyau lui-même.",
    tech: "Linux · Angel OS Core · portable runtime",
    logo: "/angel-os/logo.png",
    alt: "Angel OS",
    code: "linux.runtime -> angelOS.core -> distributions + applications",
  },
  {
    step: "02",
    title: "React construit les interfaces",
    text: "React, TypeScript, Tailwind CSS, Vite et Framer Motion composent les interfaces web : pages publiques, blog, Movix et centre de contrôle administrateur.",
    tech: "React · TypeScript · Tailwind · Vite · Framer Motion",
    domain: "react.dev",
    alt: "React",
    code: "browser -> react.ui -> applications",
  },
  {
    step: "03",
    title: "Le routeur relie interface et services",
    text: "TanStack Router et TanStack Start assurent aujourd'hui le routage web et les fonctions serveur. Angel Native API Router complète cette couche pour standardiser middleware et traitements internes.",
    tech: "TanStack Start · Angel Native API Router",
    domain: "tanstack.com",
    alt: "TanStack",
    code: "ui -> router -> server.functions -> core",
  },
  {
    step: "04",
    title: "Angel OS orchestre le système",
    text: "Event Bus, Module Registry, Request Queue, capacités, mémoire, synchronisation et services natifs forment le noyau système. Angel OS doit continuer à fonctionner même si Angel OS IA est indisponible.",
    tech: "Angel OS Core · Event Bus · Module Registry · Sync",
    logo: "/angel-os/logo.png",
    alt: "Angel OS Core",
    code: "system.module -> eventBus -> core.services",
  },
  {
    step: "05",
    title: "Les workflows savent reprendre",
    text: "Le Durable Workflow Engine découpe les opérations importantes en étapes, checkpoints et retries. Une tâche interrompue peut reprendre depuis sa dernière étape fiable.",
    tech: "Durable Workflow Engine · checkpoints · retries",
    logo: "/angel-os/logo.png",
    alt: "Workflows Angel OS",
    code: "workflow.start -> checkpoint -> retry -> resume",
  },
  {
    step: "06",
    title: "Angel OS garde la mémoire du système",
    text: "Angel Memory Index recherche transversalement dans les contenus indexés. Angel Event Log conserve la chronologie et Angel Telemetry mesure succès, erreurs et latences.",
    tech: "Memory Index · Event Log · Telemetry",
    logo: "/angel-os/logo.png",
    alt: "Mémoire Angel OS",
    code: "event -> memory.index + event.log + telemetry",
  },
  {
    step: "07",
    title: "Angel OS IA est une distribution distincte",
    text: "Angel OS IA dépend du noyau Angel OS et ajoute les fournisseurs IA, la conversation, l'analyse, la génération, les agents et les automatisations intelligentes. Le noyau ne dépend jamais d'Angel OS IA.",
    tech: "Angel OS IA · providers · agents · génération · analyse",
    logo: "/angel-os/logo.png",
    alt: "Angel OS IA",
    code: "angelOS.IA -> angelOS.core   // jamais l'inverse",
  },
  {
    step: "08",
    title: "Les moteurs externes et natifs se complètent",
    text: "Le Hybrid Orchestrator combine les fournisseurs externes et les moteurs Angel Native en cascade, race, merge ou mode adaptatif. Les services déjà fonctionnels restent utilisés lorsqu'ils renforcent l'ensemble.",
    tech: "Hybrid Orchestrator · external + native",
    logo: "/angel-os/logo.png",
    alt: "Hybrid Orchestrator",
    code: "external.providers + native.engines -> hybrid.result",
  },
  {
    step: "09",
    title: "Angel Release et Angel Deploy distribuent une même version",
    text: "Une release identifie version, commit et checksum. Angel Deploy peut envoyer cette même release vers Vercel, un Angel Node Linux ou d'autres cibles sans faire de Vercel une dépendance conceptuelle du noyau.",
    tech: "Angel Release · Angel Deploy · multi-target",
    logo: "/angel-os/logo.png",
    alt: "Angel Deploy",
    code: "release -> vercel + angel.node + future.targets",
  },
  {
    step: "10",
    title: "Angel Gateway sélectionne les nœuds sains",
    text: "Vercel peut devenir un nœud parmi d'autres. Angel Gateway classe les cibles selon santé, priorité et latence. Guardian détecte les anomalies et Recovery choisit retry, fallback, rollback ou resynchronisation.",
    tech: "Angel Gateway · Guardian · Recovery",
    logo: "/angel-os/logo.png",
    alt: "Angel Gateway",
    code: "health -> gateway.rank -> healthy.node",
  },
  {
    step: "11",
    title: "Le stockage est multi-couches",
    text: "Les données courantes restent sur les services fiables existants. Angel Native ajoute persistance et cache complémentaires. Google Drive sert d'archive privilégiée pour médias lourds, sauvegardes, exports et pièces jointes volumineuses.",
    tech: "Production data · Angel Native · Google Drive",
    domain: "drive.google.com",
    alt: "Google Drive",
    code: "data -> primary + native + drive.archive",
  },
  {
    step: "12",
    title: "GitHub versionne, Vercel sert, Angel OS coordonne",
    text: "GitHub reste la source de vérité du code. Vercel peut continuer à servir le web. Angel OS coordonne les releases, workflows, nœuds, événements, données et mécanismes de reprise. Aucun de ces rôles ne doit être confondu avec Angel OS IA.",
    tech: "GitHub · Vercel · Angel OS · Angel OS IA",
    domain: "github.com",
    alt: "GitHub",
    code: "github.code -> angelOS.release -> targets; angelOS.IA -> core",
  },
] as const;
