export const siteFlow = [
  {
    step: "01",
    title: "Le visiteur ouvre le site",
    text: "angel-leclerc.fr s'ouvre dans un navigateur ou comme PWA installée sur le téléphone.",
    tech: "Navigateur · PWA · CDN",
    domain: "google.com",
    alt: "Navigateur web",
    code: "request -> angel-leclerc.fr",
  },
  {
    step: "02",
    title: "React construit l'interface",
    text: "React affiche les pages, le blog, la boutique et l'administration. TypeScript structure le code et Vite prépare l'application.",
    tech: "React · TypeScript · Vite",
    domain: "react.dev",
    alt: "React",
    code: "browser -> react.ui -> components",
  },
  {
    step: "03",
    title: "TanStack organise les routes",
    text: "TanStack Router et TanStack Start gèrent la navigation, les pages et le chargement des données.",
    tech: "TanStack Router · TanStack Start",
    domain: "tanstack.com",
    alt: "TanStack",
    code: "react.ui -> tanstack.router -> route",
  },
  {
    step: "04",
    title: "Angel OS fournit le noyau",
    text: "Le site initialise Angel OS via son adaptateur web. Le Core apporte les événements, modules, paramètres et capacités communes sans contrôler le design.",
    tech: "Angel OS Core · Event Bus · Module Registry",
    logo: "/angel-os/logo.png",
    alt: "Angel OS",
    code: "route -> angelOS.web -> core.eventBus",
  },
  {
    step: "05",
    title: "Angel OS IA ajoute les outils personnels",
    text: "Depuis ChatGPT ou directement depuis l'espace administrateur, je peux donner un ordre. Angel OS IA orchestre ensuite les automatisations, l'administration et les outils nécessaires.",
    tech: "Angel OS IA · commandes · automatisations · modules personnels",
    logo: "/angel-os/logo.png",
    alt: "Angel OS IA",
    code: "instruction -> angelOS.IA -> private.modules",
  },
  {
    step: "06",
    title: "ChatGPT et les IA assistent certaines tâches",
    text: "ChatGPT/OpenAI peut recevoir mes instructions, aider à rédiger, analyser, modifier le code ou déclencher les outils reliés à Angel OS. D'autres modèles peuvent aussi être branchés.",
    tech: "ChatGPT · OpenAI · autres modèles IA",
    domain: "chatgpt.com",
    alt: "ChatGPT",
    code: "instruction -> ai.provider -> action",
  },
  {
    step: "07",
    title: "Supabase garde les données",
    text: "Supabase fournit encore PostgreSQL, l'authentification et le stockage pour certaines données dynamiques pendant la migration progressive vers une architecture Angel OS plus autonome.",
    tech: "Supabase · PostgreSQL · Auth · Storage",
    domain: "supabase.com",
    alt: "Supabase",
    code: "server -> supabase -> postgres",
  },
  {
    step: "08",
    title: "Les fonctions serveur parlent aux services externes",
    text: "E-mails, OAuth, statistiques, paiements, IA et autres API passent par des fonctions serveur quand l'opération ne doit pas être exécutée directement dans le navigateur.",
    tech: "Server functions · APIs · OAuth · e-mail",
    domain: "vercel.com",
    alt: "Fonctions serveur",
    code: "client -> server.function -> external.api",
  },
  {
    step: "09",
    title: "GitHub garde le code source",
    text: "GitHub reste la source de vérité du code. Les changements sont versionnés ici ; Lovable peut encore servir ponctuellement pour certaines modifications ou prototypes quand c'est utile.",
    tech: "GitHub · Git · Lovable ponctuel · open source",
    domain: "github.com",
    alt: "GitHub",
    code: "change -> github.main -> version",
  },
  {
    step: "10",
    title: "Vercel construit et publie",
    text: "Vercel récupère le code, lance le build et sert la version publiée via son infrastructure et son CDN.",
    tech: "Vercel · build · deployment · CDN",
    domain: "vercel.com",
    alt: "Vercel",
    code: "github.main -> vercel.build -> cdn -> user",
  },
] as const;
