export const siteFlow = [
  {
    step: "01",
    title: "Le visiteur ouvre le site",
    text: "angel-leclerc.fr s'ouvre dans un navigateur ou comme PWA installée sur le téléphone.",
    tech: "Navigateur · PWA · CDN",
    domain: "google.com",
    alt: "Navigateur web",
    code: "request -> angel-leclerc.fr",
  },
  {
    step: "02",
    title: "React construit l'interface",
    text: "React affiche les pages, le blog, la boutique et l'administration. TypeScript structure le code et Vite prépare l'application.",
    tech: "React · TypeScript · Vite",
    domain: "react.dev",
    alt: "React",
    code: "browser -> react.ui -> components",
  },
  {
    step: "03",
    title: "TanStack organise les routes",
    text: "TanStack Router et TanStack Start gèrent la navigation, les pages et le chargement des données.",
    tech: "TanStack Router · TanStack Start",
    domain: "tanstack.com",
    alt: "TanStack",
    code: "react.ui -> tanstack.router -> route",
  },
  {
    step: "04",
    title: "Angel OS fournit le noyau",
    text: "Le site initialise Angel OS via son adaptateur web. Le Core apporte les événements, modules, paramètres et capacités communes sans contrôler le design.",
    tech: "Angel OS Core · Event Bus · Module Registry",
    logo: "/angel-os/logo.png",
    alt: "Angel OS",
    code: "route -> angelOS.web -> core.eventBus",
  },
  {
    step: "05",
    title: "Angel OS IA ajoute les outils personnels",
    text: "Administration, automatisations, projets, candidatures, statistiques, studio et fonctions d'intelligence artificielle vivent au-dessus du Core.",
    tech: "Angel OS IA · automatisations · modules personnels",
    logo: "/angel-os/logo.png",
    alt: "Angel OS IA",
    code: "core -> angelOS.IA -> private.modules",
  },
  {
    step: "06",
    title: "ChatGPT et les IA assistent certaines tâches",
    text: "ChatGPT/OpenAI sert notamment à la rédaction assistée, la recherche structurée, l'analyse, le prototypage et certaines automatisations. D'autres modèles peuvent être branchés.",
    tech: "ChatGPT · OpenAI · autres modèles IA",
    domain: "chatgpt.com",
    alt: "ChatGPT",
    code: "angelOS.IA -> ai.provider -> response",
  },
  {
    step: "07",
    title: "Supabase garde les données",
    text: "Supabase fournit PostgreSQL, l'authentification et le stockage pour les articles, comptes, paramètres et autres données dynamiques.",
    tech: "Supabase · PostgreSQL · Auth · Storage",
    domain: "supabase.com",
    alt: "Supabase",
    code: "server -> supabase -> postgres",
  },
  {
    step: "08",
    title: "Les fonctions serveur parlent aux services externes",
    text: "E-mails, OAuth, statistiques, paiements, IA et autres API passent par des fonctions serveur quand l'opération ne doit pas être exécutée directement dans le navigateur.",
    tech: "Server functions · APIs · OAuth · e-mail",
    domain: "vercel.com",
    alt: "Fonctions serveur",
    code: "client -> server.function -> external.api",
  },
  {
    step: "09",
    title: "GitHub garde le code source",
    text: "Le dépôt contient le site et le dossier public angel-os. Chaque modification est versionnée et peut être comparée ou réutilisée.",
    tech: "GitHub · Git · open source",
    domain: "github.com",
    alt: "GitHub",
    code: "code -> git.commit -> github.main",
  },
  {
    step: "10",
    title: "Vercel construit et publie",
    text: "Vercel récupère le code, lance le build et sert la version publiée via son infrastructure et son CDN.",
    tech: "Vercel · build · deployment · CDN",
    domain: "vercel.com",
    alt: "Vercel",
    code: "github.main -> vercel.build -> cdn -> user",
  },
] as const;
