/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as EntrepriseRouteImport } from './routes/entreprise'
import { Route as DesabonnementRouteImport } from './routes/desabonnement'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ActualitesIndexRouteImport } from './routes/actualites/index'
import { Route as CommuniquesReponseArticleChniTombolaPatrimoineRouteImport } from './routes/communiques/reponse-article-chni-tombola-patrimoine'
import { Route as ArticlesReponseArticleChniTombolaPatrimoineRouteImport } from './routes/articles/reponse-article-chni-tombola-patrimoine'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as ActualitesSlugRouteImport } from './routes/actualites/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseRoute = EntrepriseRouteImport.update({
  id: '/entreprise',
  path: '/entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DesabonnementRoute = DesabonnementRouteImport.update({
  id: '/desabonnement',
  path: '/desabonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommuniquesReponseArticleChniTombolaPatrimoineRoute =
  CommuniquesReponseArticleChniTombolaPatrimoineRouteImport.update({
    id: '/communiques/reponse-article-chni-tombola-patrimoine',
    path: '/communiques/reponse-article-chni-tombola-patrimoine',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesReponseArticleChniTombolaPatrimoineRoute =
  ArticlesReponseArticleChniTombolaPatrimoineRouteImport.update({
    id: '/articles/reponse-article-chni-tombola-patrimoine',
    path: '/articles/reponse-article-chni-tombola-patrimoine',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/desabonnement': typeof DesabonnementRoute
  '/entreprise': typeof EntrepriseRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/parcours': typeof ParcoursRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/reponse-article-chni-tombola-patrimoine': typeof ArticlesReponseArticleChniTombolaPatrimoineRoute
  '/communiques/reponse-article-chni-tombola-patrimoine': typeof CommuniquesReponseArticleChniTombolaPatrimoineRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/desabonnement': typeof DesabonnementRoute
  '/entreprise': typeof EntrepriseRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/parcours': typeof ParcoursRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/reponse-article-chni-tombola-patrimoine': typeof ArticlesReponseArticleChniTombolaPatrimoineRoute
  '/communiques/reponse-article-chni-tombola-patrimoine': typeof CommuniquesReponseArticleChniTombolaPatrimoineRoute
  '/actualites': typeof ActualitesIndexRoute
  '/articles': typeof ArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/desabonnement': typeof DesabonnementRoute
  '/entreprise': typeof EntrepriseRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/parcours': typeof ParcoursRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/reponse-article-chni-tombola-patrimoine': typeof ArticlesReponseArticleChniTombolaPatrimoineRoute
  '/communiques/reponse-article-chni-tombola-patrimoine': typeof CommuniquesReponseArticleChniTombolaPatrimoineRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/desabonnement'
    | '/entreprise'
    | '/mentions-legales'
    | '/parcours'
    | '/politique-confidentialite'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/articles/$slug'
    | '/articles/reponse-article-chni-tombola-patrimoine'
    | '/communiques/reponse-article-chni-tombola-patrimoine'
    | '/actualites/'
    | '/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/desabonnement'
    | '/entreprise'
    | '/mentions-legales'
    | '/parcours'
    | '/politique-confidentialite'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/articles/$slug'
    | '/articles/reponse-article-chni-tombola-patrimoine'
    | '/communiques/reponse-article-chni-tombola-patrimoine'
    | '/actualites'
    | '/articles'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/desabonnement'
    | '/entreprise'
    | '/mentions-legales'
    | '/parcours'
    | '/politique-confidentialite'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/articles/$slug'
    | '/articles/reponse-article-chni-tombola-patrimoine'
    | '/communiques/reponse-article-chni-tombola-patrimoine'
    | '/actualites/'
    | '/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DesabonnementRoute: typeof DesabonnementRoute
  EntrepriseRoute: typeof EntrepriseRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ParcoursRoute: typeof ParcoursRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesReponseArticleChniTombolaPatrimoineRoute: typeof ArticlesReponseArticleChniTombolaPatrimoineRoute
  CommuniquesReponseArticleChniTombolaPatrimoineRoute: typeof CommuniquesReponseArticleChniTombolaPatrimoineRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise': {
      id: '/entreprise'
      path: '/entreprise'
      fullPath: '/entreprise'
      preLoaderRoute: typeof EntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desabonnement': {
      id: '/desabonnement'
      path: '/desabonnement'
      fullPath: '/desabonnement'
      preLoaderRoute: typeof DesabonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communiques/reponse-article-chni-tombola-patrimoine': {
      id: '/communiques/reponse-article-chni-tombola-patrimoine'
      path: '/communiques/reponse-article-chni-tombola-patrimoine'
      fullPath: '/communiques/reponse-article-chni-tombola-patrimoine'
      preLoaderRoute: typeof CommuniquesReponseArticleChniTombolaPatrimoineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/reponse-article-chni-tombola-patrimoine': {
      id: '/articles/reponse-article-chni-tombola-patrimoine'
      path: '/articles/reponse-article-chni-tombola-patrimoine'
      fullPath: '/articles/reponse-article-chni-tombola-patrimoine'
      preLoaderRoute: typeof ArticlesReponseArticleChniTombolaPatrimoineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DesabonnementRoute: DesabonnementRoute,
  EntrepriseRoute: EntrepriseRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ParcoursRoute: ParcoursRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ActualitesSlugRoute: ActualitesSlugRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesReponseArticleChniTombolaPatrimoineRoute:
    ArticlesReponseArticleChniTombolaPatrimoineRoute,
  CommuniquesReponseArticleChniTombolaPatrimoineRoute:
    CommuniquesReponseArticleChniTombolaPatrimoineRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
