/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as EntrepriseRouteImport } from './routes/entreprise'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActualitesIndexRouteImport } from './routes/actualites/index'
import { Route as CommuniquesReponseArticleChniTombolaPatrimoineRouteImport } from './routes/communiques/reponse-article-chni-tombola-patrimoine'
import { Route as ActualitesSlugRouteImport } from './routes/actualites/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseRoute = EntrepriseRouteImport.update({
  id: '/entreprise',
  path: '/entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommuniquesReponseArticleChniTombolaPatrimoineRoute =
  CommuniquesReponseArticleChniTombolaPatrimoineRouteImport.update({
    id: '/communiques/reponse-article-chni-tombola-patrimoine',
    path: '/communiques/reponse-article-chni-tombola-patrimoine',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/entreprise': typeof EntrepriseRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/parcours': typeof ParcoursRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/communiques/reponse-article-chni-tombola-patrimoine': typeof CommuniquesReponseArticleChniTombolaPatrimoineRoute
  '/actualites/': typeof ActualitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/entreprise': typeof EntrepriseRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/parcours': typeof ParcoursRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/communiques/reponse-article-chni-tombola-patrimoine': typeof CommuniquesReponseArticleChniTombolaPatrimoineRoute
  '/actualites': typeof ActualitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/entreprise': typeof EntrepriseRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/parcours': typeof ParcoursRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/communiques/reponse-article-chni-tombola-patrimoine': typeof CommuniquesReponseArticleChniTombolaPatrimoineRoute
  '/actualites/': typeof ActualitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/entreprise'
    | '/mentions-legales'
    | '/parcours'
    | '/politique-confidentialite'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/communiques/reponse-article-chni-tombola-patrimoine'
    | '/actualites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/entreprise'
    | '/mentions-legales'
    | '/parcours'
    | '/politique-confidentialite'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/communiques/reponse-article-chni-tombola-patrimoine'
    | '/actualites'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/entreprise'
    | '/mentions-legales'
    | '/parcours'
    | '/politique-confidentialite'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/communiques/reponse-article-chni-tombola-patrimoine'
    | '/actualites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  EntrepriseRoute: typeof EntrepriseRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ParcoursRoute: typeof ParcoursRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  CommuniquesReponseArticleChniTombolaPatrimoineRoute: typeof CommuniquesReponseArticleChniTombolaPatrimoineRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise': {
      id: '/entreprise'
      path: '/entreprise'
      fullPath: '/entreprise'
      preLoaderRoute: typeof EntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communiques/reponse-article-chni-tombola-patrimoine': {
      id: '/communiques/reponse-article-chni-tombola-patrimoine'
      path: '/communiques/reponse-article-chni-tombola-patrimoine'
      fullPath: '/communiques/reponse-article-chni-tombola-patrimoine'
      preLoaderRoute: typeof CommuniquesReponseArticleChniTombolaPatrimoineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  EntrepriseRoute: EntrepriseRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ParcoursRoute: ParcoursRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ActualitesSlugRoute: ActualitesSlugRoute,
  CommuniquesReponseArticleChniTombolaPatrimoineRoute:
    CommuniquesReponseArticleChniTombolaPatrimoineRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
