-- Legacy newsletter cron migration intentionally disabled.
--
-- This migration previously attempted to alter a pg_cron job and call a
-- Lovable endpoint with an embedded credential. That design is no longer part
-- of Angel OS: GitHub/native server integrations are the source of truth, and
-- secrets must never be committed to migrations.
--
-- Keep this historical migration as an explicit no-op so fresh/preview
-- Supabase environments can replay the migration chain even when pg_cron is
-- unavailable, without recreating the obsolete external job.
select 1;
