// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getFreshSupabaseSession } from './client'

// Global serverFn auth attachment must use the same validated session as the
// protected middleware. Attaching the raw localStorage session can leak a stale
// bearer into calls when a refresh token was rotated or the session was revoked.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const session = await getFreshSupabaseSession()
    const token = session?.access_token?.trim()
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
