const QWANT_SEARCH='https://www.qwant.com/?l=fr&q=';
const LOCAL_SEARCH=new URL('search.html',window.location.href).href;
const state={tabs:[],activeId:null,bookmarks:[],history:[],settings:{blockTrackers:true,httpsFirst:true,guardian:true}};
const $=id=>document.getElementById(id),tabsEl=$('tabs'),viewport=$('viewport'),address=$('address'),panel=$('panel');
const QWANT_CSS=`body{font-family:Arial,Helvetica,sans-serif!important;background:#fff!important;color:#202124!important}main,[role="main"]{max-width:980px!important;margin-left:auto!important;margin-right:auto!important}a{text-decoration:none!important}footer{opacity:.65!important}`;
function uid(){return`t${Date.now()}${Math.random().toString(16).slice(2)}`}
function active(){return state.tabs.find(t=>t.id===state.activeId)}
function escapeHTML(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function isLocalSearch(url){return typeof url==='string'&&url.startsWith('file:')&&url.includes('/search.html')}
function displayAddress(url){return isLocalSearch(url)?'':url||''}
function normalizeInput(raw){const v=raw.trim();if(!v)return LOCAL_SEARCH;if(/^(https?:\/\/)/i.test(v))return v;if(/^(?:[\w-]+\.)+[a-z]{2,}(?:\/|$)/i.test(v))return`https://${v}`;return`${QWANT_SEARCH}${encodeURIComponent(v)}`}
async function styleQwant(w,url){try{const u=new URL(url);if(u.hostname==='www.qwant.com'||u.hostname==='qwant.com'){await w.insertCSS(QWANT_CSS);await w.executeJavaScript(`(()=>{if(document.getElementById('flaming-search-badge'))return;const b=document.createElement('div');b.id='flaming-search-badge';b.textContent='Flaming Search · Qwant';Object.assign(b.style,{position:'fixed',right:'14px',bottom:'14px',zIndex:'2147483647',background:'#fff',color:'#3c4043',border:'1px solid #dadce0',borderRadius:'16px',padding:'7px 11px',font:'12px Arial,sans-serif',boxShadow:'0 2px 8px rgba(0,0,0,.12)'});document.documentElement.appendChild(b)})()`);} }catch{}}
function createTab(url=LOCAL_SEARCH,opts={}){const id=uid();const actual=url||LOCAL_SEARCH;const tab={id,title:opts.private?'Privé':'Flaming Search',url:actual,private:!!opts.private};const w=document.createElement('webview');w.className='webview';w.setAttribute('partition',opts.private?`temporary:${id}`:'persist:flamingbox');w.setAttribute('allowpopups','false');w.src=actual;tab.webview=w;viewport.appendChild(w);state.tabs.push(tab);wireWebview(tab);activateTab(id);renderTabs();return tab}
function wireWebview(tab){const w=tab.webview;const sync=()=>{try{tab.url=w.getURL()||tab.url}catch{}try{tab.title=w.getTitle()||tab.url||'FlamingBox'}catch{}if(state.activeId===tab.id){address.value=displayAddress(tab.url);updateSecurity(tab.url)}renderTabs()};w.addEventListener('did-start-loading',sync);w.addEventListener('did-stop-loading',async()=>{sync();await styleQwant(w,tab.url);if(!tab.private&&/^https?:\/\//i.test(tab.url||'')){await window.flamingbox.addHistory({url:tab.url,title:tab.title});await loadData()}});w.addEventListener('page-title-updated',sync);w.addEventListener('did-fail-load',sync)}
function activateTab(id){state.activeId=id;for(const t of state.tabs)t.webview.classList.toggle('active',t.id===id);const t=active();address.value=displayAddress(t?.url);updateSecurity(t?.url||'');updateBookmarkButton();renderTabs()}
function closeTab(id){const i=state.tabs.findIndex(t=>t.id===id);if(i<0)return;const[t]=state.tabs.splice(i,1);t.webview.remove();if(!state.tabs.length){createTab();return}activateTab(state.tabs[Math.max(0,i-1)]?.id||state.tabs[0].id)}
function renderTabs(){tabsEl.innerHTML='';for(const t of state.tabs){const b=document.createElement('button');b.className=`tab ${t.id===state.activeId?'active':''}`;b.innerHTML=`<span>${t.private?'◉':'●'}</span><span class="tab-title">${escapeHTML(isLocalSearch(t.url)?'Flaming Search':(t.title||'Nouvel onglet'))}</span><span class="tab-close">×</span>`;b.onclick=e=>e.target.classList.contains('tab-close')?closeTab(t.id):activateTab(t.id);tabsEl.appendChild(b)}}
function updateSecurity(url){const local=isLocalSearch(url),secure=/^https:\/\//i.test(url);$('security').style.color=(secure||local)?'#58d68d':'#f4b942';$('security').title=local?'Flaming Search local — Qwant pour les résultats':secure?'Connexion HTTPS':'Connexion non chiffrée ou page locale'}
async function toggleBookmark(){const t=active();if(!t?.url||isLocalSearch(t.url))return;const r=await window.flamingbox.toggleBookmark({url:t.url,title:t.title});state.bookmarks=r.bookmarks||[];updateBookmarkButton();renderLibrary()}
function updateBookmarkButton(){const t=active();$('bookmark').textContent=t&&!isLocalSearch(t.url)&&state.bookmarks.some(b=>b.url===t.url)?'★':'☆'}
function renderLibrary(){const fill=(id,items)=>{const root=$(id);root.innerHTML='';if(!items.length){root.innerHTML='<div class="empty">Aucun élément</div>';return}for(const x of items.slice(0,100)){const b=document.createElement('button');b.className='list-item';b.innerHTML=`<span class="item-title">${escapeHTML(x.title||x.url)}</span><span class="item-url">${escapeHTML(x.url)}</span>`;b.onclick=()=>{createTab(x.url);panel.classList.add('hidden')};root.appendChild(b)}};fill('bookmarksList',state.bookmarks);fill('historyList',state.history)}
async function refreshPrivacyStats(){try{const s=await window.flamingbox.getPrivacyStats();$('statTrackers').textContent=s.blockedTrackers||0;$('statHttps').textContent=s.httpsUpgrades||0;$('statPopups').textContent=s.popupsBlocked||0;$('statGuardian').textContent=s.guardianAlerts||0;$('statDownloads').textContent=s.downloadsObserved||0;$('statRiskyDownloads').textContent=s.riskyDownloadsBlocked||0}catch{}}
async function loadData(){const data=await window.flamingbox.getData();state.bookmarks=data.bookmarks||[];state.history=data.history||[];state.settings={...state.settings,...(data.settings||{})};$('blockTrackers').checked=!!state.settings.blockTrackers;$('httpsFirst').checked=!!state.settings.httpsFirst;$('guardian').checked=!!state.settings.guardian;renderLibrary();updateBookmarkButton()}
async function doImport(){$('importStatus').textContent='Analyse des profils Firefox, Chrome, Chromium et Edge…';try{const r=await window.flamingbox.importBrowserData();$('importStatus').textContent=`${r.importedBookmarks} favoris ajoutés. Sources : ${(r.sources||[]).join(', ')||'aucune'}.${r.warnings?.length?' '+r.warnings.join(' | '):''}`;await loadData()}catch(e){$('importStatus').textContent=`Import impossible : ${e.message}`}}
function showGuardianAlert(payload){const box=$('guardianStatus');box.textContent=payload?.message||'FlamingBox Guardian a détecté une activité inhabituelle.';box.classList.remove('hidden');setTimeout(()=>box.classList.add('hidden'),10000);refreshPrivacyStats()}
$('addressForm').onsubmit=e=>{e.preventDefault();const t=active();if(t)t.webview.src=normalizeInput(address.value)};$('newTab').onclick=()=>createTab();$('privateTab').onclick=()=>createTab(LOCAL_SEARCH,{private:true});$('back').onclick=()=>{try{if(active()?.webview.canGoBack())active().webview.goBack()}catch{}};$('forward').onclick=()=>{try{if(active()?.webview.canGoForward())active().webview.goForward()}catch{}};$('reload').onclick=()=>{try{active()?.webview.reload()}catch{}};$('home').onclick=()=>{const t=active();if(t)t.webview.src=LOCAL_SEARCH};$('bookmark').onclick=toggleBookmark;$('library').onclick=()=>{panel.classList.toggle('hidden');refreshPrivacyStats()};$('closePanel').onclick=()=>panel.classList.add('hidden');$('importData').onclick=doImport;$('passwords').onclick=()=>createTab('https://passwords.google.com/');$('security').onclick=()=>{$('securityPanel').classList.toggle('hidden');$('securityTitle').textContent='FlamingBox Shield';$('securityText').textContent='Flaming Search utilise Qwant pour les recherches. GPC, DNT, HTTPS-First, Guardian et le partitionnement du stockage restent actifs.'};$('blockTrackers').onchange=async e=>{state.settings=await window.flamingbox.updateSettings({blockTrackers:e.target.checked})};$('httpsFirst').onchange=async e=>{state.settings=await window.flamingbox.updateSettings({httpsFirst:e.target.checked})};$('guardian').onchange=async e=>{state.settings=await window.flamingbox.updateSettings({guardian:e.target.checked})};window.flamingbox.onOpenTab((url,meta)=>createTab(url,{private:false,payment:!!meta.payment}));window.flamingbox.onGuardianAlert(showGuardianAlert);window.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='l'){e.preventDefault();address.focus();address.select()}if(e.ctrlKey&&e.key.toLowerCase()==='t'){e.preventDefault();createTab()}if(e.ctrlKey&&e.key.toLowerCase()==='w'){e.preventDefault();closeTab(state.activeId)}if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='n'){e.preventDefault();createTab(LOCAL_SEARCH,{private:true})}});
(async()=>{await loadData();await refreshPrivacyStats();createTab();setInterval(refreshPrivacyStats,3000)})();
